### ISSUE TITLE
Add Ramda benchmark

### ISSUE THREAD

**Issue by slavaGanzin** [caiogondim/fast-memoize.js#11]
http://ramdajs.com/0.21.0/docs/#memoize

**Comment by caiogondim** [comment]
@slavaGanzin Adding another lib to the benchmark suite is very easy.

`npm install -D lib-you-want-to-test`
Add it to https://github.com/caiogondim/fast-memoize.js/blob/master/benchmark/index.js following the current examples.

Let me know if you have any doubts.

**Comment by slavaGanzin** [comment]
@caiogondim Thanks for help
