### ISSUE TITLE
Create decorator

### ISSUE THREAD

**Issue by caiogondim** [caiogondim/fast-memoize.js#2]

**Comment by caiogondim** [comment]
Will not implement now since decorator support is not even on latest Node.js

**Comment by dolsem** [comment]
Is this worth revisiting?

**Comment by dolsem** [comment]
@caiogondim I've created a [fork](https://github.com/dolsem/fast-memoize.js) with decorator support, let me know if you are interested in a PR. If it's too early in your opinion, just be advised that there's an implementation that potentially can be merged.
