### ISSUE TITLE
what does arguments[0] = memoized do?

### ISSUE THREAD

**Issue by ZhengHe-MD** [caiogondim/fast-memoize.js#28]
sorry. This is not a bug report. Just a personal question. I just don't understand what this line means https://github.com/caiogondim/fast-memoize.js/blob/master/src/index.js#L83. can you explain why?

**Comment by caiogondim** [comment]
🤔  There is no need for that. Maybe it was a bad git merge.
You care to make a PR just deleting that line?

**Comment by caiogondim** [comment]
I removed this line.
