### ISSUE TITLE
Object literal property shorthand breaks UglifyJS with Webpack.

### ISSUE THREAD

**Issue by phyllisstein** [caiogondim/fast-memoize.js#31]
Hey there! I just noticed when attempting to run this library through Webpack's UglifyJS plugin that [`index.js:19`](https://github.com/caiogondim/fast-memoize.js/blob/master/src/index.js#L19) causes it to choke. Apparently the object literal property shorthand isn't supported yet, causing UglifyJS to throw this error: `SyntaxError: Unexpected token punc «,», expected punc «:»`.

Would it be possible to use the older, more verbose syntax in this case? Thanks in advance for considering it.

**Comment by phyllisstein** [comment]
Switching to [`webpack-contrib/uglify-js-plugin`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) and an ES2015-friendly branch of Webpack did the trick. Nag withdrawn!

**Comment by heynick** [comment]
I'm having the same issue. webpack.optimize.UglifyJsPlugin simply doesn't uglify when the fast-memoize package is included.

I'd love to see a solution where there wasn't a need to customise the uglify plugin and Webpack version in order to include it.

**Comment by Cap32** [comment]
I'm having the same issue. I think this library should provide an ES5 version for old version browsers and `uglify-js`.
