### ISSUE TITLE
Use babel to compile ES2015

### ISSUE THREAD

**Issue by SamyPesse** [caiogondim/fast-memoize.js#34]
Since `2.2.0`, this module is no longer compatible with non-latest versions of Node and most browsers.

It'd be great to use [Babel](https://babeljs.io/) to compile ES2015 before publishing on NPM.

Here is one of my repository doing it (https://github.com/GitbookIO/node-gitbook-api), you can setup the same config with `.babelrc`, `.npmignore` and the `prepublish` in `package.json`.

**Comment by caiogondim** [comment]
Indeed.
Considering as a bug and will apply Babel before publishing.

**Comment by sebas5384** [comment]
yep! I can confirm this as a bug.

**Comment by caiogondim** [comment]
As discussed on this [PR](https://github.com/caiogondim/fast-memoize.js/pull/42)
We can't use Babel, since it will make the code slower.

I removed all fancy ES2015+ from the code and it should run on every ES5 environment.
Let me know if you find more bugs.

**Comment by ankerek** [comment]
Without babel compilation I get this error:
`Uncaught ReferenceError: cacheDefault is not defined`

**Comment by caiogondim** [comment]
@ankerek Sorry for that, I forgot to remove one `const`
Can you retry?

**Comment by caiogondim** [comment]
New version published https://www.npmjs.com/package/fast-memoize

**Comment by ankerek** [comment]
Works fine now. Thanks

**Comment by caiogondim** [comment]
You're welcome.
Sorry for the mess.
