### ISSUE TITLE
Reference Link goes to 401

### ISSUE THREAD

**Issue by pbrinkmeier** [caiogondim/fast-memoize.js#4]
The Link at line 94 of the readme ([this](https://talideon.com/weblog/2005/07/javascript-memoization.cfm) URL at [that](https://github.com/caiogondim/fast-memoize.js/commit/ddf31830b12a168f808a0a431eeb9354a5f6f0bf) commit) results in a `401 Authorization Required` HTTP response as of today (2016-06-30).

**Comment by caiogondim** [comment]
Seems the whole website is down https://talideon.com/

**Comment by caiogondim** [comment]
I will let it there for historic reasons.

**Comment by pbrinkmeier** [comment]
Just checked - the website is up again, link still goes to a 401 though
