### ISSUE TITLE
Default argument breaks correct memoization

### ISSUE THREAD

**Issue by Alex-Krautmann** [caiogondim/fast-memoize.js#64]
I am running this in webpack and have tried on requirebin.

```javascript
const fastMemoize = require('fast-memoize');
                            
const memoConcat = fastMemoize((arg1, arg2 = 'default') => {
  // fastMemoize does not work correctly with default arguments
  const value = arg1 + '-' + arg2;
  return value;
});

console.log(memoConcat('foo', 'bar')); // -> incorrectly returns 'foo-default'

```

**Comment by planttheidea** [comment]
This is a known limitation, as variadic arguments are not supported. Internally [function.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) is used, and default arguments prevent accurate determinations with this field.

**Comment by Alex-Krautmann** [comment]
@planttheidea Thanks, good to know. I imagine getting past this might bloat the package, but it is a bit unfortunate as I am weary to include this in a project where I might have to explain this on every usage via comment. The risk is that other devs might not realize this limitation and bugs could surface.
