### ISSUE TITLE
Doesn't work with inputs that have default value declaration.

### ISSUE THREAD

**Issue by ckwong90** [caiogondim/fast-memoize.js#68]
for example:

```javascript
const foo = (bool, num = 5) => bool ? {num} : {def: "default"}
expect(foo.length).toEqual(2) //Error: foo.length === 1 instead of 2

const memFoo = memoize(foo);
expect(memFoo(true, 5) === memFoo(true, 6)).toBe(false) //Error is true
expect(memFoo(true) === memFoo(true, 6)).toBe(false) //Error is true
```
Maybe add this to the limitation section in docs with the workaround

```javascript
const foo = (bool, num) => {
   num = num || 5; //initialize default value here
   return bool ? {num} : {def: "default"}
}
```

**Comment by ricardobeat** [comment]
Classic:

> We've discussed this extensively before and there doesn't seem to be many plausible use cases for the function length property.

https://esdiscuss.org/topic/function-length-and-default-parameters

There are even worse cases: https://medium.com/@robinpokorny/function-length-property-is-not-to-be-trusted-27c3b2d468d5

If using default args you should enforce the _variadic_ strategy with: 

```js
const memFoo = memoize(foo, { strategy: memoize.strategies.variadic })
```

This should definitely be mentioned in the 'Gotchas' section of the README.
