### ISSUE TITLE
Does not appear to be the fastest.

### ISSUE THREAD

**Issue by anywhichway** [caiogondim/fast-memoize.js#7]
We were just getting ready to release our memoization code when yours was announced on Node Weekly. Ours also handles N arguments and appears to be faster than fast-memoize or lodash, although we have a lot more testing we want to do, e.g. comparisons of scalability with 1,2,3,4,5 arguments. We also don't handle objects as arguments properly at this time. Here at AnyWhichWay we believe choice and variety are really good for the community, but you might want to tame down your claim about being the fastest. Here is the link: https://github.com/anywhichway/iMemoized.

**Comment by Salakar** [comment]
@anywhichway you're using `new Proxy()` which has very limited platform support so far, only just made it fully into node 6 (as in via new Proxy() - which you use). So while yours may be the fastest it surely isn't the most compatible, unlike this one.

> Here at AnyWhichWay we believe choice and variety are really good for the community, but you might want to tame down your claim about being the fastest. Here is the link: https://github.com/anywhichway/iMemoized.

Here, by myself, all alone 😢, I believe stating in open source repositories what platforms said package can actually be run on is really good for the community (like this one clearly nailed), so you may want to tame you claim about being partially the fastest, because it's only on a handful of platforms. Here is the link: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

![image](https://cloud.githubusercontent.com/assets/5347038/16543046/f19d8932-40b9-11e6-9f5e-698254b5dbb1.png) 👀


Nice use of proxy though, not seen many libs using it yet. 👍 And ofc, yes I am joking around. ;p

**Comment by anywhichway** [comment]
We are not really trying to make a claim we are the fastest or the "fastest possible". We have done way too few benchmarks to really know. Thanks on the Proxy use. Agree on your comment regarding regarding compatibility, we have made a note in our README to point out that iMemoize.memoize can be used across platforms, but full class memoizing cannot. Also, thanks for the prod! It compelled us to finish automating cross-browser testing.

**Comment by caiogondim** [comment]
Hello @anywhichway 
I'm reopening the issue since I believe there is a constructive conversation we can have here.
I was on vacation and just got back.

Will write a more elaborate message about:
- raison d'être of the lib
- the name (lots of people are seeing this as a buzzfeed or stubborn title)
- speed
- open source

Give me a couple days.

**Comment by anywhichway** [comment]
Sure, no problem! :-)

**Comment by anywhichway** [comment]
In order to be able to publish an article, we reluctantly "downgraded" our code so that is can support Safari and Edge, both of which are way behind the standards and also far slower than Firefox and Chrome ;-(.

**Comment by caiogondim** [comment]
Do you have a benchmark test?
Could you put your lib in the benchmark suite test?

**Comment by anywhichway** [comment]
There is a client side benchmark here: https://github.com/anywhichway/iMemoized/blob/master/test/benchmark.html

Will take a look at your benchmark test suite and see if we can add

**Comment by anywhichway** [comment]
To add and test iMemoize, just install the package iMemoize and add the lines:

let imemoized = require('iMemoized').memoize;

...

let memoizediMemoized = imemoized (fibonacci)
...

 .add('imemoize', () => {
    memoizediMemoized (fibNumber)
  })

**Comment by Salakar** [comment]
@anywhichway might be worth doing a PR on https://github.com/mikaelbr/proxy-fun to add your lib, it's a general list of modules using proxy / showcase of what you can do. Trending today also

**Comment by anywhichway** [comment]
Thanks!

**Comment by caiogondim** [comment]
@anywhichway, I'm finally properly responding this issue.

### raison d'être of the lib
I was studying about tail call optimization, recursive algorithms and memoization to write a blog post. And was frustated that underscore and lodash (some very popular libraries in JS land) did not support N arguments for memoization.

Then I started hacking and in a couple hours finished a working prototype. After this I plugged a benchmark suite and ran it against all the most popular memoization implementations just to be sure it was not *that* slow in comparison. And it wasn't.

### The fastest memoization library
Now I feel sorry for the buzzfeed-like name. The idea is not to be stubborn or to brag my code is the best in the world, but to *study and learn* on how to do the fastest possible memoization library in JavaScript.

For that i broke the problem into 3 pieces:
- *strategy*
- *cache*
- *serializer*

Then I wrote different implementations for each piece, and run a combination of each implementation. It was:
- **2** different implementations for **strategy**
- **1** for **serializer** (couldn't find anything but `JSON.stringify` that worked properly)
- **3** for **cache**

Which, in the end, resulted in **6** different algorithms combined.
The next step was to run **each combination** on the benchmark suite and wait for the computer to give me the answer. I used the lib `benchmark` to get statistical significant results. A data-driven approach.

When I say it is the fastest library possible in JS I mean:
- Data says so
- Fastest so far
- It will be updated as more performatic approaches appears

This library has the purpose to run in production without bugs (hey, it's has 100% coverage) but serves, as well, as a reference to the memoization topic in JS land.

### ❤️  Open source
The cool thing about open source is that you learn a lot from other people code and ideas.

I just ran you code against the benchmark suite and your approach (using `Proxy` metaprograming) is almost **twice** faster than mine (and lodash).
But supporting legacy environments is a must for me, my current employer, and for a lot of people/companies.

I'm willing to merge your code on this lib (just checked the license for your lib and it's MIT) if you are OK with that. I just gave you commit access to the repo so we can work together.

My other idea is that we could start an organization and merge this lib with yours, so I don't get all the recognition for it and it would be easier to find collaborators as well.

Memoization is a key core lib for every language, and I would be more than happy to help to participate in a project to create and maintain the best memoization lib in JS land.

What you think?

**Comment by anywhichway** [comment]
I am certainly interested in collaborating. Coding is just a part time thing for me, a hobby i guess ... I am actually an executive:  http://msmary.edu/about-the-Mount/presidents_office/university-cabinet/Blackwell.html.

No need to "feel sorry for the buzzfeed-like name.". If you had not said what you said, I would not have taken on the challenge and we would not be where we are today!

I am somewhat less concerned with legacy compatibility in the early stages of code development only because it takes so much work and is crippling during exploratory programming. The first version of iMemoize took longer to document than it did to write!. That being said, over time I have managed to make almost anything backward compatible. Although Proxy is now supported across all browsers so it seems elimination is not necessary, see [http://caniuse.com](http://caniuse.com/#feat=proxy). The biggest blocker to Proxy adoption was actually its removal from Chrome in 2014 and lack of replacement until 2016. In the particular case of iMemoize, it would also be easy to eliminate. Also, Proxy is only used at the class and object level, iMemoize.memoize does not use a Proxy. In fact, if a Proxy for function application is used the code is 50% slower!

Since iMemoize is currently smaller and faster, I suggest that we use that for a basis. I think there are a number of ways in can be enhanced, e.g. cache timeout, collection of hit statistics, documentation, etc. Both timeout and statistics management can be done with very low overhead and would not require the inclusion of an additional package as with https://github.com/medikoo/memoizee.

We will also be able to generate general visibility through this initiative:

https://github.com/anywhichway/iSeries

I plan to put the lead contributor ids next to the package titles.

Note, I just committed this, so the npm package is not yet ready, although all the packages described have at least a v0.0.1. I also have several others almost at v0.0.1.

I am particularly interested are stylistic consistency across libraries to facilitate ease of testing, learning and use. I am also interested in isomorphic code for the same reasons.

**Comment by anywhichway** [comment]
I just updated my copy of lodash and re-ran benchmarks. It now seems to be on par with iMemoize. It also seems to be supporting multiple arguments. I will post something more formal in a few days.

**Comment by agauniyal** [comment]
Btw I saw `vanilla` in your benchmark too and wonder what is meant by `vanilla` term in this context since it doesn't seems to be a library.

**Comment by dodekeract** [comment]
@agauniyal vanilla is a conventional name for anything that's "as untouched as possible". In the context of javascript it's simply calling the function instead of using any library.

Another example is found in games. Minecraft without any mods is called "vanilla" because it's the "default flavor".

**Comment by caiogondim** [comment]
I also updated the library.
It seems to be the fastest.

Please let me know if you manage to make it even faster.
Would love to see your approach.
