### ISSUE TITLE
Not working with es6 getters

### ISSUE THREAD

**Issue by ricardomatias** [caiogondim/fast-memoize.js#71]
I have the following code
```
	get scale() {
		const createScale = (root, scaleType, noteType) => {
			console.log('MEMOIZE', root, scaleType, noteType);
			return new Scale(root, scaleType, noteType);
		};

		return memoize(createScale)(this._root, this._scaleType, this._noteType);
	}
``` 

Even though the arguments are the same, the createScale function is still called twice, thus returning different instances of Scale. Any ideas? Is this specific to ES6 class getters?

**Comment by planttheidea** [comment]
You appear to be creating a new function and executing it every time scale is called?

**Comment by planttheidea** [comment]
Well of course it is ... You are creating a new memoized function and executing it every time that `scale` is called. You should make that function a standalone function (created once, not on every execution) and then it will work as you expect.

**Comment by ricardomatias** [comment]
That sounds rather obvious.. these getters tied my brain into a knot. Thanks for the help.
